version: '3.0'

services:
  api:
    container_name: nest-api-mongo2
    depends_on:
      - redis
      - mongodb
    build:
      context: .
      target: development
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    # env_file:
    #   - .env
    environment:
      - MONGO_URL=${MONGO_URL}
      - REDIS_HOST:=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      # - REDIS_USERNAME:default
      # - REDIS_PASSWORD:fbX4PgCelRue3exBCWFETglpCkrzehiB

    ports:
      - 3000:3000
    command: yarn start:dev
  redis:
    image: redis
    ports:
      - 6379:6379
    volumes:
      - redis:/data

  mongodb:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGODB_DATABASE: service
    ports:
      - 27017:27017
    volumes:
      - mongodata:/data/db
volumes:
  mongodata:
  redis:
    driver: local
